### PR TITLE
Fixed positions of notes

### PR DESCRIPTION
**Pull request by Tsunami014**
Added the field diagram back with the correct settings to make sure everything is to scale!

### CODE REVIEW

**Comment by auscompgeek** [comment]
What isn't to scale? The field image and dimensions in WPILib 2024.2.1 should be correct.

**Comment by Tsunami014** [comment]
Yeah I was running an old version of WPILib and so updating it worked...

But all the positions were *slightly* off, which I hope I fixed :)

**Comment by Tsunami014** [comment]
Hold up, just fixing the x co-ordinates...

**Comment by Tsunami014** [comment]
There, what about now?

**Comment by auscompgeek** [comment]
How did you obtain those note positions?

**Comment by james-ward** [comment]
The poses that we have here need to be the pose of the _robot_ when it picks up the note, not the position of the note itself.

**Comment by mlists** [comment]
Seems like a dead PR

**Pull request closed without merging**
