### PR TITLE
fixed chassis units

### PR DESCRIPTION
**Pull request by fotnitfpro000**

### CODE REVIEW

**Review by mlists — COMMENTED** [review]
You missed one on line 186 I think (can't comment on lines not in the PR)

**Comment by LucienMorey** [comment]
This pr does funny things in the sim. We should find out why before merge

**Comment by mlists** [comment]
Sim is still broken

**Comment by mlists** [comment]
I think I found our bug, the sim code assumed rps. I also set a max speed rather than going of wheel speeds.

**Review by auscompgeek — APPROVED** [review]

**Pull request merged**
