### PR TITLE
remap controls to better suit beana

### PR DESCRIPTION
**Pull request by Beana1234**

### CODE REVIEW

**Review by mlists — APPROVED** [review]
I don't like this control scheme but you are the one who has to drive it 🤷

**Comment by Beana1234** [comment]
> I don't like this control scheme but you are the one who has to drive it 🤷

It will actually allow for the climber to be deployed whilst moving the robot, that is the main reason for the changes

**Comment by auscompgeek** [comment]
You could always give your codriver something to do 😛

**Comment by Beana1234** [comment]
True, although I feel simply rearranging the control scheme so the climber can be deployed and retracted with the right hand rather than the left is simpler

**Pull request merged**
