### PR TITLE
added dataclass for note/shoot position and coordinates for the notes

### PR DESCRIPTION
**Pull request by outsidermm**

### CODE REVIEW

**Comment by outsidermm** [comment]
It would be great if someone could double-check the coordinates. I was using the Field Dimension, but I’m not exactly confident in my measurement skills.

**Comment by james-ward** [comment]
As an overarching comment I think if we can make this structural change we can tweak the actual coordinates later.

For example, we will not want to be approaching all the notes at 0 degrees heading. We can tweak that later, though.

**Comment by james-ward** [comment]
These named coordinates need to be used in the autonomous routines.

**Comment by outsidermm** [comment]
> These named coordinates need to be used in the autonomous routines.

The named cords are now implemented and works fine in sim

**Comment by outsidermm** [comment]
> As an overarching comment I think if we can make this structural change we can tweak the actual coordinates later.
> 
> For example, we will not want to be approaching all the notes at 0 degrees heading. We can tweak that later, though.

Off

**Review by mlists — APPROVED** [review]

**Pull request merged**
